name: AWS Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-west-2'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ inputs.region }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: List S3 Buckets
        run: aws s3 ls
