name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Select the environment

env:
    TF_WORKING_DIR: terraform

jobs:
    deploy:
      name: Deploy website
      runs-on: ubuntu-latest
      timeout-minutes: 4
      steps:
          - name: Git checkout
            uses: actions/checkout@v3

          # - name: Install dependencies
          #   run: npm ci

          # - name: Build
          #   run: npm run build

          - name: Secretes
            run: echo ${{ env.AWSACCESSKEYID }}; echo ${{ env.AWSSECRETKEY }}

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-region: eu-west-2
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

          - name: Terraform Setup
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_version: 1.3.3

          - name: Terraform init
            id: init
            run: export TF_VAR_environment=${{ inputs.environment }}; terraform init
            working-directory: ${{ env.TF_WORKING_DIR }}

          - name: Terraform validate
            id: validate
            shell: bash
            run: export TF_VAR_environment=${{ inputs.environment }}; terraform validate
            working-directory: ${{ env.TF_WORKING_DIR }}
