name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Select the environment
jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      timeout-minutes: 4
      steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Root install
            run: npm ci
            shell: bash

          - name: Build
            run: npm run build