name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Select the environment

jobs:
    deploy:
      name: deploy website
      runs-on: ubuntu-latest
      timeout-minutes: 4
      steps:
          - name: Set environment variables
            run: |
              echo "TF_WORKING_DIR=terraform" >> $GITHUB_ENV
              echo "TF_VAR_environment=${{ inputs.environment }}" >> $GITHUB_ENV
          
          - name: Git checkout
            uses: actions/checkout@v3

          - name: Install dependencies
            run: npm ci

          - name: Build
            run: npm run build

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-region: us-west-2
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

          - name: Echo environment variables
            run: |
              echo ${{ env.TF_WORKING_DIR }}
              echo ${{ env.TF_VAR_environment }}

          - name: Terraform setup
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_version: 1.3.3

          - name: Terraform init
            id: tfinit
            run: terraform init
            working-directory: ${{ env.TF_WORKING_DIR }}

          - name: Terraform validate
            id: tfvalidate
            run: terraform validate
            working-directory: ${{ env.TF_WORKING_DIR }}
          
          - name: Terraform plan
            id: tfplan
            run: terraform plan
            working-directory: ${{ env.TF_WORKING_DIR }}

          - name: Terraform apply
            id: tfapply
            run: terraform apply -auto-approve
            working-directory: ${{ env.TF_WORKING_DIR }}

          - name: Publish artifacts
            run: |
              if [ ${{ inputs.environment }} == 'production' ]; then
                echo "Deploying to production"
                aws s3 sync dist/ s3://spyros.uk/
              else
                echo "Deploying to staging"
                aws s3 sync dist/ s3://staging.spyros.uk/
              fi